### PR TITLE
Subgridding tweaks

### PR DESCRIPTION
**Pull request by drvdputt**
- New options for the subgridding run script. See the help strings. The script has had a general rework, too.

- The `reduce_grid_info` tool in `subgridding_tools` has a new option to reduce the memory usage. The original method tries to count how many unique values a quantity has in the total grid. If the grid is very large, this can cause too much memory usage. The `cap_unique` option simply cuts of the calculation when a certain number of unique values (default 1000) has been counted. As long as the maximum number of bins for the 1d pPDFs in fit.py (default 50) is smaller than this number, this option should be safe to use.

### CODE REVIEW

**Comment by karllark** [comment]
This looks great.  Would be great to have some tests for this code.  Is that something easy to add to this pull request (probably not) or something for a separate pull request (probably)?

**Comment by drvdputt** [comment]
I just pushed two tests, one for `split_grid`, and one for `reduce_grid_info`.

I'm planning to write one for `merge_pdf1d_stats` too, but I need to think about how I can avoid having to do a full run for that. I can probably download the example trimmed seds and trimmed noise model, split them, and then do the sub-fits.

**Comment by karllark** [comment]
Is this ready for merging?

**Comment by drvdputt** [comment]
Actually, I just started writing a test for the merging function. Still not sure if this will turn out easy or hard.

I suggest that you pull these changes so @cmurray-astro, can start using the `cap_unique` option. I can then add the test for `merge_pdf1d_stats` in a separate pull request, if I can get it working properly.

**Comment by karllark** [comment]
Ok.  Merging...

**Pull request merged**
