### PR TITLE
Graphics for file flow

### PR DESCRIPTION
**Pull request by lea-hagen**
This adds visualizations of what files are created when a BEAST run is split by either subgrids or source density.  These are added to the docs and the code is in `plotting`.  To help untangle the mess of lines, some of them are color-coded to separately follow the SED grid, noise model, and photometry.

`plot_graphic_file_flow.py` has options to change the numbers of subgrids, SD bins/sub-bins, etc.  I settled on the current numbers because sometimes the graphs get rearranged in unhelpful ways.

Partially addresses #680 

--------
**Subgrid splitting**
beast-file-flow-subgrid

--------
**Source Density splitting**
beast-file-flow-sourceden

### CODE REVIEW

**Comment by lea-hagen** [comment]
I'll check on the codestyle things.  But in the meantime, @karllark do you happen know what's going on with docs error about not being able to read the image file?

**Comment by karllark** [comment]
> @karllark do you happen know what's going on with docs error about not being able to read the image file?

You need to add the png file to the `[options.package_data]` section in setup.cfg.   Png files are not automatically included (unlike py files).

**Comment by lea-hagen** [comment]
Oh right!  I'm pretty sure you've had to explain that to me a few times now 😆

**Comment by lea-hagen** [comment]
Hmm, that seems to not be the problem.  I think that line in setup.cfg is for things in the `beast` folder, not in the docs.  Looking back at #624, there weren't changes to any configuration files (except for adding the `graphviz` dependency), and as far as I can tell, those images worked fine.

**Comment by karllark** [comment]
Humm....do the docs build on your computer?  Another thought, are the permissions on those files ok?

**Comment by karllark** [comment]
Ok, the issue is the filename is wrong.  In the docs it is `images/beast-graphic-file-flow-sd.png` and the file is actually called `images/beast-graphic-file-flow-sourceden.png`.

**Comment by lea-hagen** [comment]
Thanks for catching that!!  Hopefully things are good to go now...

**Comment by lea-hagen** [comment]
It looks like the coverage test is failing because it's having download problems.  I noticed that yesterday too, but with a different file.

**Comment by karllark** [comment]
I agree the coverage tests are an unrelated download issue.

Can you fix the minor codacy issue?

**Comment by lea-hagen** [comment]
I just checked on the Codacy issue.  I'm a little confused - it says "No blank lines allowed after function docstring", but only finds one instance of it, when there are actually three functions with what I assume are blank lines after the function docstring.  Is this something you're familiar with?

**Comment by karllark** [comment]
> Is this something you're familiar with?

Nope.  If black is ok with the file, then say the word and I'll ignore the codacy check.

**Comment by lea-hagen** [comment]
Yeah, I re-blackened and nothing was changed.  I did some googling, and from discussion [here](https://github.com/PyCQA/pydocstyle/issues/361), it seems like it might be varying interpretations of one of the PEPs.

**Comment by karllark** [comment]
One last minor change.  Can you change the title of the rst page to `Graphical Models` as now there is more than one?

**Comment by lea-hagen** [comment]
Done!

**Review by karllark — APPROVED** [review]
Looks great.

**Pull request merged**
