### PR TITLE
Add Distance as 7th fitting variable

### PR DESCRIPTION
**Pull request by drvdputt**
Addresses issue #38.

### CODE REVIEW

**Comment by drvdputt** [comment]
In its current state, this branch passes the tests on my (linux) machine. The Travis tests show some weird errors with Cython though. It is unclear to me where these are coming from.

I tried a few different versions of numpy and python, but was not able to reproduce these errors.

**Comment by karllark** [comment]
The travis issues should be solved once the merge has happened.  The version of astropy-helpers needed updating.  I've now gotten onto the list for getting automated pull requests for this.  And just merged such a pull request.

**Comment by karllark** [comment]
Need some documentation.  Please look in the docs subdirectory and see if it is obvious where to put such documentation.  If not, ask and I will look and provide suggestions.

**Comment by karllark** [comment]
One complication that we need to solve is that all the examples will be moved to a separate repository (already setup in BEAST-Fitting) when the pip_installable pull request is merged.  So, conflicts!  Maybe I should just go ahead and do the merge this (and other pull requests) and then  redo the pip_installable pull request.  But maybe someone else has a clever idea for this.

**Comment by drvdputt** [comment]
So, the basic functionality for the distances should be almost there. I just have a couple of
questions/comments to make.

- general

  - There are some formatting changes in the files I modified, mostly whitespace trimming. You can    hide the latter by adding '?w=1' to the end of the github URL when viewing a diff.

- examples

  - In the data model files, the distances are given as a range (or a single number) and unit (length or mag).

  - In the run files, these values are passed to one of the functions, where the distances are calculated and applied.

  - There is a new example, which is the same as phat_small but with multiple distances. It is called phat_small_multidistance, and has its own datamodel file.

  - I put a way of loading the datamodel as a python model directly from a given file path in run_beast.py for phat_small. This way, I can run the multidistance example without having to copy phat_small/run_beast.py and phat_small/data/ (just use symlinks).

    QUESTION:
    It seems kind of hacky though, and the way of doing this has changed a couple of times (see stackoverflow link in source code), so I'll need some feedback on whether this is acceptable.

    It's hardly a necessary feature, especially since we're planning to move the examples somewhere else. But it does give the first step towards having a general run script.

- grid creation

  - In creategrid.py, there is now an apply_distance_grid function

  - This function is used in model_grid.py: make_spectral_grid().

    This function now has 'distance' and 'distance_unit' as arguments. 'distance' can be a float or [min, max, step]. distance_unit can be either units.mag or any length unit, and defaults to parsec.

    This way, I've ensured that using a single number in parsec (not a 1-element list) also works, so the tests for this function still work without modification.

    The distance grid is then created linearly in distance modulus space or directly in distance space depending on the unit given.

- plotting

  - I've modified the plot_indiv_fit script, so that it also displays the distance (even when there's only one distance)

    QUESTION:
    Is it acceptable that the distance is always added to the grid (and plotted), even if there is only one?

- documentation
  
  - 'distances' and 'distance_unit' are mentioned in the explanation about the datamodel.

**Comment by karllark** [comment]
All the changes look good.
The tests are failing now on a different issue.  Has to do with docstrings that have example code.  Just need to comment these out (e.g., ">>>" need to be removed).  The tests of the docstrings are trying to run the code with ">>>" and it is not working.

**Comment by karllark** [comment]
Probably should fix the failing tests in a separate pull request.  Then all new pull requests will be tested against the fixed code.  Safer that way.  I can have a look at fixing this issue in the next week or so.

**Comment by karllark** [comment]
Or someone else can.  :-)

**Comment by karllark** [comment]
Tests have been fixed by a separate pull request.  Hence, tests now passing - yeah!

**Pull request merged**
