### PR TITLE
updates to ASTs and source density binning

### PR DESCRIPTION
**Pull request by lea-hagen**
This has an assortment of updates to the way ASTs and source density binning is done.

ASTs:
* Option to limit the x/y of artificial stars to where there are certain filters.  Currently can only do shapes that are convex polygons (i.e., not shapes with holes) because it uses a convex hull.
* Optional input for the WCS origin (0 or 1, default is 1 for fits) for the input reference image
* bug fix: if a source density bin tile is outside of any user-defined region, it is excluded from the list of tiles before placing sources.
* bug fix: there was an issue with checking if proposed x/y is within a given boundary
* use `shapely` for some of the region manipulation (#397)

`create_background_density_map.py`/`density_map.py`:
* bug fix: WCS conversions/calculations
* add option for the width of the bin, rather than just the number of bins
* for creating a source density map, add optional flag filter to exclude sources that are `[filter]_FLAG=99`

`split_catalog_using_map.py`:
* option to split catalogs into sub-files (e.g., 6250 stars per file)

`setup_batch_beast_fit.py`:
* bug fix: path to `tools/run/` files
* bug fix: moving the `pf=None` initialization to the beginning of the code

things in `beast/tools/run/`:
* I was running a test for using backgrounds instead of source densities in the noise model, and realized these aren't compatible.  Therefore, everything is adjusted to use the nomenclature of `split_catalog_using_map.py` instead of `subdivide_obscat_by_source_density.py` (#381).  I think this also eliminates the need for `split_asts_by_source_density.py`.
* `make_ast_inputs.py` runs now
* `create_physicsmodel.py`: added code to run model generating as a script (useful for large grids that require a bunch of subgrids)

`cut_catalogs.py`:
* add option for multiple flag filters
* option to return the cut catalog instead of writing it out

`production_runs_2019` example: 
* updated to be consistent with all of the changes above

### CODE REVIEW

**Comment by lea-hagen** [comment]
@karllark do you know why the lgtm/travis builds aren't working?  I can't figure out if it's something wrong with the code.

**Comment by karllark** [comment]
This is great @lea-hagen !  I'll look at the tests and see I can figure out the problem.

**Comment by karllark** [comment]
No idea why LGTM failed.

Travis CI failed as I've had to update the files to support the adjustable stellar priors PR (#387) where there were changes in the prior numbers due to a bug in the grid weights and changes in filenames (sometime ago - more consistent naming by you I believe).  I also updated all the priors to be normalized to 1 on average to avoid numerical issues.  So, I think this PR can move forward, but there might have to be a quick 'fix' PR after this and the adjustable stellar priors PR is merged.

**Comment by karllark** [comment]
Is this PR ready for merging?  Looks good to me so will merge if so.

**Comment by lea-hagen** [comment]
There's one more thing I just remembered: `shapely` needs to be added as a package dependency.  Where do I add that?

**Comment by karllark** [comment]
Is this PR needed for the 1.3 branch?

**Comment by lea-hagen** [comment]
The last commit updates `setup.cfg` and `.travis.yml` with the package dependency (which addresses #397).  So this is ready to be merged!

**Comment by karllark** [comment]
Of course, if 1.3 it will also go into 2.0.

**Pull request merged**
