### PR TITLE
Adding Aringer AGB atmospheres

### PR DESCRIPTION
**Pull request by marthaboyer**
Edited stellib.py to include AGB atmospheres from Aringer et al. (2016). The library file is ready to go... I just need to know where to put it.

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 1 alert** when merging a0d7d6fa420a1c860e131d4c409186abcc568e8d into 164288c742e86b16b7981f88342a3f6ef4a0b640 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-1a0dc961dc52fb57cc2942658e8ef03e040d34c9)

**new alerts:**

* 1 for Missing call to \_\_init\_\_ during object initialization

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
@marthaboyer : can you email me the location of the library file?  Say on central storage and then I can copy it to the right place?

**Comment by marthaboyer** [comment]
/astro/mboyer/Science/BEAST/Aringer.AGB.grid.fits.  Let me know if you don't have permission to access.

**Comment by s-goldman** [comment]
@marthaboyer Do you remember where the library file you added came from? Did you parse the data from the filenames on the [COMARCS](http://stev.oapd.inaf.it/synphot/Cstars/cspec08.html) website. Also, do you have another file with the corresponding spectra? Karl asked me to try and implement the models and I've got a function to convert the COMARCS specific luminosities to specific surface fluxes for the BEAST.

**Pull request merged**
