### PR TITLE
Remove "mem" requirement for writing sbatch files

### PR DESCRIPTION
**Pull request by cmurray-astro**
Replaces requirement for specifying memory with number of nodes (new way of allocating SUs on Bridges EM and RM, vs. old way on Brides-Regular and -Large (which are now obsolete))

### CODE REVIEW

**Comment by cmurray-astro** [comment]
would love a review by @petiay and/or @christinawlindberg :)

**Review by petiay — APPROVED** [review]
Looks good to me, Claire.

**Comment by petiay** [comment]
The readthedocs error sounds vaguely familiar:

> ModuleNotFoundError: No module named 'setuptools._distutils'

but would anyone know specifically what the problem may be? @karllark perhaps?

**Comment by karllark** [comment]
RTD build was a transitory issue.  Builds fine now.

**Pull request merged**
