### PR TITLE
WIP: splitting run_beast into separate scripts

### PR DESCRIPTION
**Pull request by lea-hagen**
Here's the current status of breaking apart `run_beast`.  Currently consists of code for the physicsmodel, ASTs, noisemodel, and fitting.  Should be generalized for running with or without source density splitting and subgrids.

Still need to update examples and documentation.

### CODE REVIEW

**Comment by s-goldman** [comment]
@lea-hagen So the scripts we probably want to be easy to use are:
`create_physicsmodel.py`
`create_obsmodel.py`
and
`fitting.py`

**Comment by lea-hagen** [comment]
And probably also `make_ast_inputs.py`.  The other one, `helper_functions.py`, just has a few functions that are called by all of them.

**Comment by karllark** [comment]
This pull request **introduces 10 alerts** when merging 687a1e4a867cd8b8c569fa2feac5679180fd75b2 into e3704e17e91801907ba04b4efb42263cf1c8abfc - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-109c5de2fefa261bc6ce8d210f266d68359c4181)

**new alerts:**

* 7 for Unused import
* 3 for Syntax error

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
This pull request **introduces 3 alerts** when merging 62a04a51a4e6abb0b4bbc7a82ee48c2a64139920 into e3704e17e91801907ba04b4efb42263cf1c8abfc - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-162ac25277a64613c2d8e7a869d5c9466fee8b8c)

**new alerts:**

* 3 for Syntax error

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lea-hagen** [comment]
Deleting this so I can re-create the branch now that #340 is merged.

**Pull request closed without merging**
