### PR TITLE
CMD plotting code

### PR DESCRIPTION
**Pull request by petiay**
Code reads in real or simulated data from a BEAST grid and plots a CMD.
As a test, the CMD below is the output from beast_example_phat_simobs.fits (located at http://www.stsci.edu/~kgordon/beast/).

image

### CODE REVIEW

**Comment by karllark** [comment]
Great.  Thanks for this pull request.

The checks are failing as there are both tabs and spaces used for indentation.  Is this something you can fix easy?  If not, then I can merge and fix it quickly myself.

**Comment by karllark** [comment]
I have not fixed it.  Please do!  :-)

**Comment by karllark** [comment]
How is this code used?  From the commandline?  In a jupyter notebook?  Have not dealt with code with a function called 'main' before and so am curious.

**Comment by petiay** [comment]
I need to learn to code properly... I'll follow the convention in the other beast/plotting routines by using beastplotlib's initialize_parser() throigh __main__.  Will test and submit asap.

**Comment by karllark** [comment]
Ok.  Great.

**Comment by petiay** [comment]
Hoefully this version works.

**Comment by karllark** [comment]
Look good.  I'll try and test it myself soon and then merge.

**Comment by karllark** [comment]
Is the name of the script accurate?  It is plot_syncmd, but it works for both synthetic and observed CMDs.  Would it be better to change this to plot_cmd?

**Comment by karllark** [comment]
Looks great.  Here is a CMD from PHAT data in brick 21 (source density 5-6).
figure_1

**Comment by karllark** [comment]
Merging!

**Comment by petiay** [comment]
Changing the name - absolutely.  I'll do it if you haven't already.

**Comment by karllark** [comment]
I was so happy with the plot, I merged this pull request forgetting my request for a change.  If you wouldn't mind, please go ahead and change it.  I think if you push your changes, the pull request will reopen, but maybe not.  Not a big deal.  Feel free to just make a new pull request.  It would be good to have a little documentation to go with the script, so that could be a good addition to a new pull request.

**Pull request merged**
