### PR TITLE
WIP: implementing datamodel class

### PR DESCRIPTION
**Pull request by lea-hagen**
Here's the current status of the work I'm doing for #320.  I've updated the `phat_small` example to use the text file, and moved the SED reading code that was in `datamodel.py` to its own code in `tools`.  Here's an example of how it works.
```
> from beast.tools import read_datamodel
> datamodel = read_datamodel.datamodel('beast/examples/phat_small/datamodel.txt')
> 
> datamodel.surveyname
'PHAT'
> datamodel.basefilters
['F275W', 'F336W', 'F475W', 'F814W', 'F110W', 'F160W']
> datamodel.obs_colnames   # in datamodel.txt as [ f.lower() + '_rate' for f in basefilters ] 
['f275w_rate', 'f336w_rate', 'f475w_rate', 'f814w_rate', 'f110w_rate', 'f160w_rate']
> datamodel.distance_unit
Unit("mag")
> datamodel.velocity
<Quantity -300. km / s>
> datamodel.osl
CompositeStellib, <beast.physicsmodel.stars.stellib.CompositeStellib object at 0x7f173f9f98d0>
['Tlusty', 'Kurucz 2004']
> datamodel.av_prior_model
{'name': 'flat'}
```
When reading in the file, it automatically runs the same verification code as before (which is now incorporated into `read_datamodel`).  The user can always re-run the verification if they change anything:
```
> datamodel.verify_params()
```

The only(!) thing that still needs doing is incorporating this into the run_beast code.  The syntax for getting values from datamodel is the same, which helps.  But since the SED reading code had to be moved (which we've been wanting to do for a while), I'll need to find all of the places where that's used.

Any thoughts/feedback are welcomed!

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 13 alerts** when merging 6db828113910a3d10a63a7dd4aa8ae9f7b2b582a into 974fb72f3a1974d25d3a36304122464c6e86b68c - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-0ce8525812b127d9392d5e884f5153481cc22d5d)

**new alerts:**

* 12 for Unused import
* 1 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lea-hagen** [comment]
quick note - some of the imports that LGTM labels as unused are actually used, but they're in strings that are passed to `eval`/`exec`, so the code never directly sees them.

**Comment by karllark** [comment]
This pull request **introduces 5 alerts** when merging 3c151d3b24472f8983d20bc1b391454a56819ca3 into 974fb72f3a1974d25d3a36304122464c6e86b68c - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-8370217126581579aa15eb376d3b008b1acc643d)

**new alerts:**

* 4 for Unused import
* 1 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
At a minimum, you should add a comment about the "unused" imports in the code.  Better would be investigating LGTM and figuring how what comment string to add to get it to ignore these unused import (I remember this is possible, but not how to do it).  :-)

**Comment by lea-hagen** [comment]
Given how much has changed since starting this PR, I think I might need to copy over `read_datamodel.py` to a new branch and make a new PR.  Unless any git experts have other suggestions?

**Comment by karllark** [comment]
That is clearly the easiest solution.  Go for it.  Should be straightforward.

**Pull request closed without merging**
