### PR TITLE
Background + source density in one script

### PR DESCRIPTION
**Pull request by drvdputt**
Adresses #274 

There are now two different, mutually exclusive ways to specify the pixel size: --pixsize and --npix.

The make_background_density_map script now has dual functionality, using subcommands. Run --help to see how it works.

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging 3fcf92ccc445cc077e1efa4fc6ad9ff31e9a9df4 into 6ab6434d3f10e8275e75b97c1abb7c368a72be13 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-de857fdd546858a2e458f62661afb331590a7971)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 1 for Testing equality to None
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
Great!  @lea-hagen - can you have a look and this PR a review?

**Comment by drvdputt** [comment]
A couple of things that still need to be done:
- Look through the docstrings / comments. Maybe put some usage examples at the top.
- For the background map, there is some code which can make this plot:
backgroundmap-crop
It would be nice if this could also be done for the source density map, but I would have to think about the command line options then.

**Comment by karllark** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging 841f846ac68fab57f14984f4462e1006b28bb5fd into b625c1f48700551fadb97758fba6e2f94190f292 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-c2d4384674f91d711eaf596e6f2759818e7c199d)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 1 for Testing equality to None
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by drvdputt** [comment]
I updated the docstrings, and in the process I discovered a bunch of mistakes.
- The physical angle on the sky is not the same as the width of a RA bins. There is a factor cos(DEC) between them. This is important when setting up the grid using --pixsize, or when setting up a WCS. As the WCS of the map is used to check which sources belong to a pixel, there were many things wrong, which have now been fixed.
- The rotation angle for the squares of the plot was wrong. Polygons are used instead of Rectangles now, so this rotation isn't even necessary anymore. Now there are no more (visual) gaps between the tiles.
[compress14186_IC-63.gst_culled_plot_overlay.pdf](https://github.com/BEAST-Fitting/beast/files/2856682/compress14186_IC-63.gst_culled_plot_overlay.pdf)

**Comment by karllark** [comment]
Great progress!

**Comment by karllark** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging 5a33e7d15fb13c5297e111fae276bd52428b5880 into b625c1f48700551fadb97758fba6e2f94190f292 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-ad9eb5a9a72497f1aca89a92484f191f52fff337)

**new alerts:**

* 1 for Unused local variable

**fixed alerts:**

* 1 for Testing equality to None
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
I don't know.  @drvdputt ?

**Comment by drvdputt** [comment]
Yes. First of all, the workflow.rst document has a section about the background maps that needs to be reworked. 

Secondly, the production wrapper imports some functions from both the density and the background script. Since one of these scripts has been deleted, and the other one has new function signatures, this wrapper script needs to be updated also. We could either run the script itself as a subprocess, or we could call the 'main_make_map' function, with an artificially constructed argument list.

There are also some doc strings in other files where one of the two scripts is mentioned.

But before any of the documentation is changed: should create_background_density_map be renamed to something else? Or is it good as it is, with create_source_density_map just disappearing?

**Comment by drvdputt** [comment]
So, the latest bunch of commits removes all mention of create_source_density_map. Everything now points to create_background_density_map.

I also took care of the duplicated code in the run scripts, when picking AST locations with a background map or density map. There is now a single ast_density_table setting, and a single call to `pick_positions_from_map`.

I also changed some things in the production wrapper, mainly the calls to the main function of the formerly separate source density and background scripts. I think it'd be best for someone to check if the wrapper still does what it needs to do.

**Comment by karllark** [comment]
This pull request **fixes 7 alerts** when merging 920b203f09b8cd6218873454512e951b46b8602f into a02e5fb4ae79fc2b6bd2ccfb13422a8f3f4cd60c - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-febb709edf3e70c7261fc45fe1ef749aec5eda13)

**fixed alerts:**

* 5 for Unused import
* 1 for Testing equality to None
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
Looking great - thanks for all the work.
One quick comment - there is an error in building the docs.
https://travis-ci.org/BEAST-Fitting/beast/jobs/501585674

Do you see then error when you build the docs locally?  (e.g., `python setup.py build_docs`)

**Comment by karllark** [comment]
The changes look reasonable to me.  @lea-hagen : comments?  Are you able to check the code with actual examples?

**Comment by drvdputt** [comment]
> Looking great - thanks for all the work.
> One quick comment - there is an error in building the docs.
> https://travis-ci.org/BEAST-Fitting/beast/jobs/501585674
> 
> Do you see then error when you build the docs locally? (e.g., `python setup.py build_docs`)

Ok, quick fix. Just had to add a newline.

**Comment by karllark** [comment]
This pull request **fixes 7 alerts** when merging 67c84956c76eaf48168aced6e86c210fdda4374f into a02e5fb4ae79fc2b6bd2ccfb13422a8f3f4cd60c - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-75b9406f488a553f83dacbb8879ef3ce9566f22c)

**fixed alerts:**

* 5 for Unused import
* 1 for Testing equality to None
* 1 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
Looks good.  Merging.

**Pull request merged**
