### PR TITLE
divide run_beast.py into separate files

### PR DESCRIPTION
**Pull request by lea-hagen**
The current version of `run_beast.py` wasn't going to work with production run settings.  So I've divided it into separate files.  A wrapper for them, to show how they're used for a production run, will be in #328. 

My general philosophy was to put as many of the details (such as file names) in the background.  Therefore, each of the main functions take in the minimum number of inputs: generally (1) whether catalogs are divided by source density, (2) how many subgrids to use (where 1 means no subgrids), and/or (3) how many parallel processes to use.

Here's a summary of changes:
* in the `beast/run_beast` folder:
  * `create_physicsmodel.py`
  * `make_ast_inputs.py`
  * `create_obsmodel.py`
  * `run_fitting.py`
  * `merge_files.py`
  * helper functions: `helper_functions.py` (mostly for subgrids) and `create_filenames.py`
* `setup_batch_beast_fit.py` and `merge_beast_stats.py`: updated to be compatible with the new code
* phat_small example is updated, which will require some changes to the reference files (the naming scheme has slightly changed and it now saves 500 `lnp` points instead of 60)

Still to do before merging:
* update documentation
* update the other examples
* still need to confirm `merge_files.py` works as expected for subgrids... will probably discuss that in a separate issue

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 26 alerts** when merging ae83316169b7c824f6ee9d41269a12d0be29f7a8 into de50ca4d05ba681fd6e2450fc12841d728c9eb23 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-3724d3ae629cf3d0bddb13a8aa05960bdba63296)

**new alerts:**

* 18 for Unused import
* 7 for Unused local variable
* 1 for Variable defined multiple times

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
This pull request **introduces 5 alerts** when merging 52c6622bb1f28cf90978fc90813e81004bb9fb40 into de50ca4d05ba681fd6e2450fc12841d728c9eb23 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-a47127549fd3134a311a4799f7c212ba9baa31e6)

**new alerts:**

* 5 for Unused local variable

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
There are a few unused variables.  Is this what was expected?  If so, they should be removed.  If not, then they should be checked to see why they are not being used.

**Comment by lea-hagen** [comment]
Updates:
* I confirmed that the merging code works (see plots in #189)
* With the production run settings added in #328, the METAL production example is unnecessary (and a bit outdated), so I've removed it.
* Updated the `phat_small` example: running it is exactly the same (so no documentation update is necessary), but the code it calls is now the new things in `run_beast/` rather than the large chunks of code that were there.

**Pull request merged**
