### PR TITLE
get_noisemodelcat now returns a dictonary

### LINKED ISSUE #64: Unclosed noisemodel files
When running phat_small example, the following files are left unclosed:
beast_example_phat/beast_example_phat_noisemodel.hd5
beast_example_phat/beast_example_phat_noisemodel_trim.grid.hd5

Is there a missing close statement somewhere?

### PR DESCRIPTION
**Pull request by karllark**
Change get_noisemodelcat to return a dictionary instead of an open pytables hdf5 file object. 
This fixes the unclosed files bug (closes #64).

This required changes to a few files to remove the specific pytables hdf5 interface to the noisemodel data.  Now the interface is a standard python dictionary.

Added a simple test for get_noisemodelcat.

### CODE REVIEW

**Comment by karllark** [comment]
@lea-hagen - another review request.  A few of the tools you've wrote required some changes.

If you don't have time, tell me and I'll look for another reviewer.

**Comment by lea-hagen** [comment]
Thanks for tackling this change!  I'll take a look tomorrow or Monday.  Are you confident that you found all of the places that the noisemodel object is used, or should I also do a look around to confirm?

**Comment by karllark** [comment]
I think I found them all.  But cannot be sure.  If you can check - that would be great.

**Comment by karllark** [comment]
I agree you should add automated tests!  I also agree that saving the testing of the subgrid till then make sense.  So, I'll go ahead and merge this after I merge the other PR.  Thanks for the review!

**Pull request merged**
