### PR TITLE
WIP: Star type probability and related tools

### PR DESCRIPTION
**Pull request by lea-hagen**
This adds `tools/star_type_probability.py` to calculate the probability that a star is of a given type (#373).  Each type of star is its own function, so new functions can easily be added for more types of stars.  To address the questions in #467, there's also a function to compare the results from the full set of lnPs to a randomly selected subset of lnPs.

Getting this to work also required editing some other parts of code:
* `tools/subgridding_tools.py`: Added a `merge_lnp` function to combine lnPs across subgrids.  There's an optional `threshold` argument (like the one in `fit.py`) to eliminate lnPs much smaller than the maximum, which can help reduce file size.
* `tools/run/merge_files.py`: includes `merge_lnp` in the merging for subgrids
* `tools/read_beast_data.py`: Migrated over from `read_beast.py` in the MegaBEAST (BEAST-Fitting/megabeast#40).  It has functions to extract data from the files for the noise model, SED grid, and lnPs, and return them as dictionaries.  For the SED grid, if the parameter list is `None`, it will print out all of the parameters in the file (relevant to #433).  The code also has a function to get the parameter values associated with the lnPs.
* `tools/trim_many_via_obsdata.py`: If a trimmed file already exists, it will now skip to the next one in the input file.  (This isn't immediately related to finding star types, but it came up while I was testing a start-to-finish run with the lnP merging.)

------------------------------

The probability of being a star type is currently calculated by adding up the probabilities associated with the physical parameters (e.g., `M_ini > 10` & `Av > 0.5`) and dividing by the total probability.  This only uses the 500 sparsely sampled lnPs.  As is currently being discussed in #467, it seems like 500 may not be enough, or perhaps we need to choose the saved lnPs differently.  The issue is that the high-probability region of the grid may not be getting sampled well enough, so the star type probabilities are subject to significant fluctuations depending on which lnPs get chosen to save.  Until that's resolved, this PR will be WIP.

### CODE REVIEW

**Comment by karllark** [comment]
I wonder if this PR should be split into two PRs.  One for the tools that merge the lnps from subgrid runs and one to address determining the probabilities of different types of stars/sightlines.  @lea-hagen : is this possible?  Having two PRs would make it easier to know which changes are for which purpose and make reviewing/accepting the PRs easier.

**Comment by karllark** [comment]
I wonder if it would be possible to setup the code that generates the probability that a fit is for a certain type of star/sightline to be similar to what is done get compute the 1D pPDFs?  Specifically saving the indexes for each type so that the probability can be computed quickly for a large number of stars.  I think that will be the use case.  Setting it up like this would mean it could be run as part of the fitting *or* as a post-processing step - equally quickly.

**Comment by karllark** [comment]
I see the strength of having each type of star/sightline defined by a function, but this could generate a significant amount of overhead especially when the types we want to compute before large.  Would there not be a way to specify this using a dictionary that specifies the min/max for each BEAST parameter?  And then passing this to a single function that works on said dictionary?   It might even be better if the types could be specified in an ascii table - making it very easy to expand the list of types for which probabilities to be computed.

**Comment by karllark** [comment]
Having some set of the star/sightline probabilities computed during the fit will likely be very useful.  And I'm betting that there is a default set that makes a great deal of sense to do for all BEAST fits.  For example, hot stars, cool stars, young stars, old stars, red giants, lightly extinguished stars, moderately extinguished, heavily extinguished.  Just name a few.

**Comment by lea-hagen** [comment]
> I wonder if this PR should be split into two PRs. One for the tools that merge the lnps from subgrid runs and one to address determining the probabilities of different types of stars/sightlines. @lea-hagen : is this possible? Having two PRs would make it easier to know which changes are for which purpose and make reviewing/accepting the PRs easier.

Definitely possible.  I'm not sure logistically how to do that... maybe close this one, and cherry-pick the relevant commits onto new branches?

------

> I wonder if it would be possible to setup the code that generates the probability that a fit is for a certain type of star/sightline to be similar to what is done get compute the 1D pPDFs? Specifically saving the indexes for each type so that the probability can be computed quickly for a large number of stars. I think that will be the use case. Setting it up like this would mean it could be run as part of the fitting _or_ as a post-processing step - equally quickly.

I'm not quite sure if I'm following the question.  The code does use the whole array of stars (shape of `(n_lnp, n_stars)`), so the operations are relatively optimized.

------

> I see the strength of having each type of star/sightline defined by a function, but this could generate a significant amount of overhead especially when the types we want to compute before large. 

Could you clarify why would this make a lot of overhead?

> Would there not be a way to specify this using a dictionary that specifies the min/max for each BEAST parameter? And then passing this to a single function that works on said dictionary? It might even be better if the types could be specified in an ascii table - making it very easy to expand the list of types for which probabilities to be computed.

I thought about this option, but I couldn't figure out a simple way to arbitrarily define a region.  For instance, I recall that the cuts @s-goldman made for selecting AGB stars are some sort of polygon in two parameters.  If cuts involve something more complicated than min/max, or require more than a couple of parameters, the ascii/dictionary method could get really messy.  However, I'm very much open to changing that if it would be less awful than I'm imagining.

------

> Having some set of the star/sightline probabilities computed during the fit will likely be very useful. And I'm betting that there is a default set that makes a great deal of sense to do for all BEAST fits. For example, hot stars, cool stars, young stars, old stars, red giants, lightly extinguished stars, moderately extinguished, heavily extinguished. Just name a few.

Absolutely.  If we can finalize a set in the next month or so, I can incorporate them into the METAL production runs.

**Comment by karllark** [comment]
> > I wonder if it would be possible to setup the code that generates the probability that a fit is for a certain type of star/sightline to be similar to what is done get compute the 1D pPDFs? Specifically saving the indexes for each type so that the probability can be computed quickly for a large number of stars. I think that will be the use case. Setting it up like this would mean it could be run as part of the fitting _or_ as a post-processing step - equally quickly.
> 
> I'm not quite sure if I'm following the question. The code does use the whole array of stars (shape of `(n_lnp, n_stars)`), so the operations are relatively optimized.

Ok.  That does cut down on the overhead.  But this setup does mean that the code has to be run as a post-processing step.  In other words, it would be hard to efficiently run it like the fitting is done - star-by-star.

**Comment by karllark** [comment]
> > I see the strength of having each type of star/sightline defined by a function, but this could generate a significant amount of overhead especially when the types we want to compute before large.
> 
> Could you clarify why would this make a lot of overhead?

The overhead is that a function needs to be written for all star/sightline types, including the simple ones that could be defined by a simple box.  Maybe there would be a way to have a dictionary for the simple box-like types and then use a function for the others?

**Comment by lea-hagen** [comment]
I'm going to close this PR so its contents can be split into two PRs.

**Pull request closed without merging**
