### PR TITLE
updates to simulate_obs.py

### PR DESCRIPTION
**Pull request by lea-hagen**
I made two major updates to `beast.tools.simulate_obs.py`:
* move code into a function, so it can be imported OR used with argparse
* to support subgrids, the physics and noise model inputs are now lists (where each subgrid has its corresponding noise model), and stars are drawn successively from each of them.

This is fine to merge now, or wait until I've finished a workflow example of running the simulated observations through the BEAST.

### CODE REVIEW

**Comment by lea-hagen** [comment]
Looks like the LGTM alert is related to python 2.7, where dividing two integers would give an integer instead of a float.

**Comment by karllark** [comment]
Any indication of how  to change this on the website? I looked in  the past and have not had success.

**Comment by karllark** [comment]
Just checking - this still will work if you pass just a single file, right?

**Comment by lea-hagen** [comment]
Using argparse, yes, it can take just one file of each.  (In confirming that assertion, I realized a couple of the `add_argument` settings needed fixing, so that's updated in the latest commit.)

Calling as a function, it currently requires a list of files.  If you think it would be useful to also take in a string, I can do a quick update.

**Comment by karllark** [comment]
I think you can fix the issue  when calling with a single element instead of an array by using numpy.atlest_1d in the beginning of the function.

**Comment by lea-hagen** [comment]
MAGIC!!!

Should be good to go now.

**Pull request merged**
