### PR TITLE
Increase number of PDF bins

### LINKED ISSUE #570: Change default `max_nbins` for PDFs?
I just (re-)noticed that there's a parameter in `Q_all_memory` (beast/fitting/fit.py), `max_nbins`, that sets the maximum number of bins for the 1D and 2D PDFs.  The current default is 50.  So even if the grid is more finely sampled, the PDFs will have at most 50 bins.  Does this default still make sense, or should it be increased for production runs?  I'm unsure if the coarser PDF resolution will impact science goals.  Currently, their only use is for doing cuts for star types.

### PR DESCRIPTION
**Pull request by lea-hagen**
Per #570, increasing the max number of bins from 50 to 100.  Happy to change this to 200 (or some other number) if preferred.  This change should be added to both v1.4 and v2.0.

I expect that this will change the stats (slightly) and PDFs for non-gridded parameters (mass, luminosity, temperature, etc), so the tests will probably fail.  We'll have to coordinate updating files with #558 and #559.

Closes #570.

### CODE REVIEW

**Comment by lea-hagen** [comment]
@karllark it looks like a setting needs to be changed in Codacy to let it analyze the v1.4 branch.

**Comment by karllark** [comment]
Codacy for v1.4 enabled.

**Comment by karllark** [comment]
One of the tests failed - `test_fit_grid.py`.  Can you set the max_nbins in the tests to 50?  Then the tests will continue to work and be robust to future changes to max_nbins.

**Comment by lea-hagen** [comment]
That sounds good.  Since `max_nbins` only exists in `Q_all_memory`, I'll need to propagate it through all the layers that call it, but that should be straightforward.  The question, though, is whether to add it as an input to `tools/run/run_fitting.py` or put it in datamodel.

**Comment by karllark** [comment]
It should at least be propagated so that the tests can be run.  I'm not sure that this needs to be exposed in datamodel.py - at least at this point.  Not sure we want everyone to have to decide what value they want for this parameter.

**Comment by lea-hagen** [comment]
I think I edited my comment accordingly just as you commented!  The tests should run fine now.

**Comment by karllark** [comment]
Setting up a PR to v1.4 is ok, but in the future can you do the PR to master and then comment that it needs to be done for v1.4?  No change needed for this PR, just that is the way that makes things the most straightforward for me.  Thanks.

**Comment by lea-hagen** [comment]
> Setting up a PR to v1.4 is ok, but in the future can you do the PR to master and then comment that it needs to be done for v1.4? No change needed for this PR, just that is the way that makes things the most straightforward for me. Thanks.

I'm happy to do that!  However, for some reason, when I tried the merge to master, it listed a whole bunch of commits and lots of line changes.  Perhaps that's because I made the branch from v1.4 instead of master?  I'll try branching from master next time.

**Comment by karllark** [comment]
Good point.  Open the PR to whichever branch makes sense.  I can see that fixing v1.4 could mean you really do want to branch from v1.4.  It will get fun merging a fix into both at some point I imagine.

**Pull request merged**
