### PR TITLE
Update convex hull code

### PR DESCRIPTION
**Pull request by christinawlindberg**
1. Updated convex hull path with concave hull method to make it possible to fit fields with concave footprints. Regular convex footprints are still fittable with this method.
2. Create a diagnostic plot to visualize the area where ASTs can be placed.
E.g. 
image

### CODE REVIEW

**Comment by christinawlindberg** [comment]
Would fix #779

**Comment by galaxyumi** [comment]
I tried this on LUVIT galaxies, which have more complicated footprints from multiple cameras as well as more significant density variation within one HST pointing. Unfortunately this doesn't fix the problem reported in #779. Also, the shapely package version seems to affect its usage. The version @christinawlindberg used was 2.0.1 for her development.

**Comment by karllark** [comment]
@christinawlindberg can you response to @galaxyumi's comment above?

**Comment by karllark** [comment]
Closing.   New PR will be opened base don a branch.

**Pull request closed without merging**
