### PR TITLE
beast_settings (previously datamodel) class

### LINKED ISSUE #320: new datamodel class
I'm working on changing `datamodel.py` to a class.  It will take a text file as an input and create the `datamodel` class, and will be able to interpret python functions, strings, and units.  I'm also incorporating the verification code into it.

### LINKED ISSUE #508: rename datamodel.py
As we've had a recent wave of new users, I've heard feedback that the name `datamodel` for a file that has settings is confusing.  I propose that we rename it to something like `beast_settings` or `beast_input`.  I think it would be very straightforward to find-replace all instances of `datamodel` in the code/documentation.

### LINKED ISSUE #576: Incorrect datamodel import
After #573, `datamodel` no longer imports correctly.  It imports the new stubs rather than importing the local user-defined `datamodel.py`.  Here's the error for phat_small:

```
In [1]: %run run_beast.py -potf
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/astro/dust_kg3/lhagen/stsci/beast-examples_lea-hagen/phat_small/run_beast.py in <module>
     65     if args.physicsmodel:
     66
---> 67         create_physicsmodel.create_physicsmodel(nsubs=1, nprocs=1)
     68
     69     if args.ast:

/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/tools/run/create_physicsmodel.py in create_physicsmodel(nsubs, nprocs, subset)
     57     importlib.reload(datamodel)
     58     # check input parameters
---> 59     verify_params.verify_input_format(datamodel)
     60
     61     # filename for the SED grid

/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/tools/verify_params.py in verify_input_format(datamodel)
    120
    121     parameters = [
--> 122         datamodel.z,
    123         datamodel.obsfile,
    124         datamodel.astfile,

AttributeError: module 'beast.tools.run.datamodel' has no attribute 'z'
```

### LINKED ISSUE #587: Streamline BEAST settings as a class?
Rather than updating the datamodel.py file (or new BEAST settings file) locally, it would be great to implement a class so that variables can be updated in the workflow/code. Not sure if this is already happening (@lea-hagen)?

### PR DESCRIPTION
**Pull request by lea-hagen**
This is an updated version of #326 that implements `datamodel` as a class (with a text file of input parameters) rather than using a `datamodel.py` file that gets imported.  

Here's an example of how it works, copied over from #326.  I'll open a PR in beast-examples with the datamodel.txt file, but it's nearly identical to datamodel.py.
```
> from beast.tools import read_datamodel
> datamodel = read_datamodel.datamodel('beast-examples/phat_small/datamodel.txt')
> 
> datamodel.surveyname
'PHAT'
> datamodel.basefilters
['F275W', 'F336W', 'F475W', 'F814W', 'F110W', 'F160W']
> datamodel.obs_colnames
['f275w_rate', 'f336w_rate', 'f475w_rate', 'f814w_rate', 'f110w_rate', 'f160w_rate']
> datamodel.distance_unit
Unit("mag")
> datamodel.velocity
<Quantity -300. km / s>
> datamodel.osl
CompositeStellib, <beast.physicsmodel.stars.stellib.CompositeStellib object at 0x7f173f9f98d0>
['Tlusty', 'Kurucz 2004']
> datamodel.av_prior_model
{'name': 'flat'}
```
When reading in the file, it automatically runs the verification code (`beast/tools/verify_params.py`).  The user can always re-run the verification if they change anything:
```
> datamodel.verify_datamodel()
```

Still to do:
* finish testing that everything works as expected
* update docs

closes #320 
closes #576
closes #508
closes #587

### CODE REVIEW

**Comment by lea-hagen** [comment]
I looked up how to ignore the unused imports (which, as mentioned in #326, are still used in the `eval` calls).  For codacy, I think @karllark has to manually choose to ignore them ([link](https://support.codacy.com/hc/en-us/articles/360009180134-Issues-View)).  For LGTM, it looks like there might be a way to add a suppression code in a comment ([link](https://lgtm.com/help/lgtm/alert-suppression), all the way at the bottom).

**Comment by karllark** [comment]
Maybe we can discuss this issue of unused imports.  I would like to better understand the issue and find out if there is another way to handle them.  Maybe at the next BEAST HackDay?

**Comment by lea-hagen** [comment]
It also just occurred to me that the imports could stay in datamodel.txt.  They'd get evaluated in the same way as all of the other lines.

**Comment by lea-hagen** [comment]
Per conversation with @karllark, I've eliminated datamodel and changed it to beast_settings.  Hooray!!

Closes #508

**Comment by karllark** [comment]
Excellent - github actions tests are running for this PR!  They are not passing, but at least they are running even though this PR was started before github actions was added to the master.

**Comment by lea-hagen** [comment]
Yeah!  I just rebased (there was a minor conflict that needed to be resolved manually), so perhaps that's why they're running now.  They're pretty neat!

**Comment by karllark** [comment]
rebase for the win!

**Comment by lea-hagen** [comment]
I updated the docs, added a simple test of `beast_settings.py`, and put in the related PR for examples (https://github.com/BEAST-Fitting/beast-examples/pull/13).  Ready to be reviewed in time for the hack day!

**Comment by lea-hagen** [comment]
Looks like the test I added is failing.  It works when I just run it with python, but I don't know how to decipher tox yet.

**Comment by karllark** [comment]
The test is failing in that it can't find the the `hst_whitedwarf_frac_covar.fits` file.  The beast library files are not present in the test environment, so they need to be downloaded.  This is a common issue and can be solved by having your test download this file using the `download_rename` function in tests/helpers.py.   And providing the location of this file to your test.

**Comment by karllark** [comment]
One idea would be to remove the test from the PR and add this test in a separate PR.  That way this PR could be merged making the BEAST run.  Then during the HackDay you could work on getting the test to run.

**Comment by karllark** [comment]
Getting the lib files worked!

**Comment by karllark** [comment]
Ok to merge this PR? 

I've got a plan to make the getting of libfiles more streamlined (use this for all the tests and only have to run the command once - I hope).

**Comment by lea-hagen** [comment]
Hooray!  Glad it finally worked!

**Pull request merged**
