### PR TITLE
Test for star_type_probability

### PR DESCRIPTION
**Pull request by lea-hagen**
This adds a test for `star_type_probability.py`.  Funny enough, as part of doing this, I found a bug - when the required 2D PDF didn't exist, it returned None (instead of a list of None), so the results could be returned as a dictionary, but not saved as a table in a fits file.

This will require two files to be added to the remote data folder: `beast_example_phat_pdf2d.fits` and `beast_example_phat_startype.fits`.  @karllark, they add up to ~8 MB, so I'll email you their paths in my directory.

Partially addresses #531

### CODE REVIEW

**Comment by karllark** [comment]
Yeah you found a bug.  One of the benefits of writing the tests is that when writing them you might find bugs!

**Comment by karllark** [comment]
Is this ready for merging?  Or were you going to add additional tests?  I just looked at the coverage change and there is about a quarter of the tool file that is not covered.  Just checking.

**Comment by lea-hagen** [comment]
Good question.  The other ~25% is from two things:
* Checking the order of parameters (e.g., `'M_ini+Av'` or `'Av+M_ini'`): This order is set by the order of parameters in the SED grid file, so I wouldn't expect it to change, but I suppose you never know.  It's also easier (and faster) than reading in a grid file to see what the order should be.  I'm not sure how to test this.
* Missing 2D PDF: I suppose I could do another phat_small run that doesn't save the needed parameters, and upload that as a separate cached file.

**Comment by lea-hagen** [comment]
I just added another test for when the needed 2D PDFs aren't saved.  I'll email you the reference files again, @karllark.

I also had to change the returned value from None to NaN.  Updated the docs to include that.

**Pull request merged**
