### PR TITLE
Adding in slack, test changes, and commit video documentation

### PR DESCRIPTION
**Pull request by karllark**
Will address issue #167.

### CODE REVIEW

**Comment by karllark** [comment]
Can you post the errors text you are getting when running the test code?
Please tell me what version of python and numpy you are using.  If the tests did not complete, then you will not see the htmlconv directory giving the coverage results.

For the documentation, it is in the docs/_build/html directory.

**Comment by lea-hagen** [comment]
Turns out I was trying to run it on a mac instead of linux, so the first tests are fine, and I can see the html files in the htmlconv directory.  But I haven't been able to figure out how to get the html for the docs to appear.  After running `python setup.py test build_docs`, it finishes with a green line that says `17 passed, 7 skipped`, but there is no _build in the docs directory.

**Comment by karllark** [comment]
Good catch.  The command should be 'python setup.py build_docs'.  I've updated the doc file to have the correct command.
I was wondering if the tests failed because of being run on a Mac.  I've been thinking we might need to have a way to alter the tests based on the computer used.  Either by having a different set of files to download or by allowing for small differences.  I have opened #169 for this issue.

**Comment by lea-hagen** [comment]
That solved it!  Looks good.

**Pull request merged**
