### PR TITLE
subgrid merging updates (lnP fixes, new stats info columns)

### PR DESCRIPTION
**Pull request by lea-hagen**
This fixes a few things for merging lnPs across subgrids:
* updates to how `tables` does things with hd5 files
* a few bugs that I missed when writing the merging code in #493

### CODE REVIEW

**Comment by karllark** [comment]
Ready for a review?

**Comment by lea-hagen** [comment]
Yes, ready to be reviewed.

I squeezed in one more merging update.  When merging stats files across subgrids, this adds two more columns:
* `best_gridsub_tag`: the subgrid with the best fit
* `Pmax_indx`: the index (within that subgrid) of the Pmax value
When merging across source density bins, there was already a column (`reorder_tag`) that saved the original pre-merged bin info.  Now that's extended to subgrids too.

**Review by karllark — APPROVED** [review]
Looks good.  I have some worries given the subgrid regression tests have been disabled as they have been failing due to a number of updates since the cached files were created.   Did you want to investigate updating the subgrid cached files and re-enabling the tests for this PR or a later PR?

**Comment by lea-hagen** [comment]
Yeah, I agree that's a problem.  I was thinking of working on updating the tests and cached files at the next hack day.

**Comment by karllark** [comment]
Ok.  Then I will merge this PR now and expect a new PR in Oct.  :-)

**Pull request merged**
