### PR TITLE
Cleanup noisemodels

### PR DESCRIPTION
**Pull request by karllark**
Removed code that is not used (not updated and no current use case).
PEP8 changes as well.
Some documentation added to describe the three possible noise models.  More documentation needed, especially how to use/activate the different models.

### CODE REVIEW

**Comment by lea-hagen** [comment]
Looks good, but two quick questions:

`perCameraASTs`: We don't currently have a use case, but is it possible that it would still be useful for other people?  Or is it really just the same as `MultiFilterASTs` but with separate input tables?

Documentation: were you planning to add more info about the noise models now, or sometime in a future pull request?

**Comment by karllark** [comment]
We have never used perCameraASTs to my knowledge.  And it is just a way to input AST results in separate files instead of in one file to my understanding.  Hence, why I removed it.
More documentation would always be good.  Anything in particular you would like me to add?  I may try and get the API documentation (docstrings) working for at least.  A good time to request docs even if I just end up opening a new issue.

**Comment by karllark** [comment]
Partially addresses issue #16.

**Comment by lea-hagen** [comment]
Is there an example that includes the `Trunchen` noise model?

**Comment by karllark** [comment]
Not that in the repository.  I should have one around.  I'll put in a issue for this.

**Comment by karllark** [comment]
Thanks.

**Pull request merged**
