### PR TITLE
allow best legend location; fix matplotlib 3.3 rqmt

### PR DESCRIPTION
**Pull request by petiay**
An explicitly-specified legend location in the lower right of the individual star fit plot sometimes overlapped the legend with a fit line. `matplotlib.legend` can be asked to choose the best location for minimum overlap. A future update can include a legend location option.

The change in the keyword for symlog was based on a MatplotlibDeprecationWarning received just today:
`MatplotlibDeprecationWarning: The 'linthreshy' parameter of __init__() has been renamed 'linthresh' since Matplotlib 3.3; support for the old name will be dropped two minor releases later.`
The latest Matplotlib minor release - [3.3.3](https://pypi.org/project/matplotlib/#history) - took place recently on Nov. 11, 2020, and I believe this is why we may not have run into this issue yet. (I ran into it when testing the legend location option change).

### CODE REVIEW

**Comment by karllark** [comment]
Can you add a description for this PR (you can edit this - it is the "first" comment)?   It is good practice to provide a short description in a PR so that it is clear what is being added/fixed.

One question that came to my mind was why the change to the keyword for the symlog?

**Comment by petiay** [comment]
Good point - commented above.

**Comment by karllark** [comment]
Thanks for the description - now all makes sense!

**Review by karllark — APPROVED** [review]
Looks great.

**Pull request merged**
