### PR TITLE
tools for subgridding

### PR DESCRIPTION
**Pull request by drvdputt**
#189 

The current production example allows the user to run the beast in parallel for subsets of stars, but this means that the whole grid needs to be loaded for each process.

This pull request introduces a number of tools and changes that allow per-subgrid parallel processing:
- Function for splitting the grid into chunks of equal size.
- Modifications to fit.py to make the output of the subgrid runs compatible.
- Function that merges the individual pdf1d and stats files

This way, beast processes can be run on the same machine, without the memory overhead.

Most of the tools are in ``beast.tools.subgridding_tools``. Maybe there is a better location, as most of the current tools are actually scripts, instead of utility functions.

A run script is not yet included, but I have one available is that is of interest. Tips on how to modify the example run script are given in ``docs/subgrid_parallelism.rst``.

### CODE REVIEW

**Comment by karllark** [comment]
Great to see you wrote documentation as well.

**Comment by karllark** [comment]
Were you planning on including an example model run for the subgridding?

**Comment by drvdputt** [comment]
I think I can provide a new output file. Although now I'm wondering why adding the distance didn't give an error for the testing, since the reference file wouldn't have had those columns.

As for the example, the phat_small data and datamodel can be used, but with a new run script. I think adding this script will be useful to show how the parallel processing works. I currently have such a script for my own use, which also contains a custom --ast section.

I think I'll add it as-is, and then we can polish it up later.

**Comment by karllark** [comment]
sounds like a good plan

**Comment by drvdputt** [comment]
The tests succeed when I ignore the new column by changing
`for tcolname in table_new.colnames:`
to
`for tcolname in table_cache.colnames:`
in `test_fit_grid.py`. Which is good news.

@karllark, I'll send you then new file by email.

**Comment by drvdputt** [comment]
I think the current state is good enough for a merge. 

I will be using this new functionality in the nearby future, so then I'll see how it does in production.

**Comment by karllark** [comment]
Ok.  Going to merge.  The failing test should go away when merged into the master (I think).

**Pull request merged**
