### PR TITLE
code to make chi2 histogram

### PR DESCRIPTION
**Pull request by lea-hagen**
This adds code (`plot_chi2_hist.py`) to make a histogram of the `chi2_min` values.  Documentation is added too.

I also made a small change to `plot_cmd_with_fits.py`: there is a new keyword to choose whether to plot all sources (convert fluxes into magnitudes) or only use sources with magnitudes <99 (which filters out stars with sharpness/crowding cuts).

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 6 alerts** when merging 66bdc69914a1935a41e0a1622796acd8e69d3d19 into afdc5d92928c12aacc5c173ab0a9bdc41ecca099 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-a285e28f547884d4516a334b1d27b2b700460bee)

**new alerts:**

* 3 for Unused local variable
* 3 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
This pull request **introduces 1 alert** when merging da606a7c1bfcae5dd018ed9b24e25fcc543e1207 into afdc5d92928c12aacc5c173ab0a9bdc41ecca099 - [view on LGTM.com](https://lgtm.com/projects/g/BEAST-Fitting/beast/rev/pr-ad22cae3012b2fb36a35b629d9d96859c5900e8f)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by karllark** [comment]
Is this PR ready for merging?

It would be good to fix the unused import identified by LGTM.

**Comment by lea-hagen** [comment]
I removed the extra import, so it's ready to merge.

**Pull request merged**
