### PR TITLE
Fix extinction/dust_extinction discrepancies

### PR DESCRIPTION
**Pull request by lea-hagen**
Addresses #359:
* all BEAST extinction curve prescriptions have the attribute `x_range`, and if the input wavelength is outside of that range, it throws an error (conveniently using `_test_valid_x_range` from `dust_extinction`)
* In `beast.physicsmodel.model_grid`, `make_spectral_grid` takes the extinction curve (`datamodel.extLaw`) as an optional input.  If it's set, any parts of the spectra with wavelengths outside of `x_range` are discarded.

### CODE REVIEW

**Comment by karllark** [comment]
This PR causes the CI testing to fail with the out-of-range error for the dust extinction model.  What needs to be changed in beast/physicsmodel/tests/test_extinguished_sed_grid.py to get back to the previous solution?

see: https://travis-ci.org/BEAST-Fitting/beast/jobs/560175889

**Comment by karllark** [comment]
Maybe an updated version of the spectral grid file to cache for comparison during the tests?  And maybe an update to beast/physicsmodel/stars/tests/test_spectral_grid.py instead?

**Comment by lea-hagen** [comment]
I had forgotten to update the examples, so that's done now.  Since this update fundamentally changes the SED grid, I think it would be best to update the cached version.  I created a new one by running the phat_small example -- where do I put it?

**Comment by karllark** [comment]
Somewhere on central storage and tell me where it is.  I'll update the cached version then.  Wish there was a better way, but not yet.

**Comment by lea-hagen** [comment]
just sent you a message with the file path

**Comment by karllark** [comment]
An update to beast/physicsmodel/stars/tests/test_spectral_grid.py is needed.  It is still building the old - larger grid.

**Comment by lea-hagen** [comment]
Looks like it's ok now?

**Comment by karllark** [comment]
Looks great.  The current failure is an unrelated documentation issue.  So, going to merge.

**Pull request merged**
